name: 'daily fetch'

on:
  schedule:
    - cron: '0 4 * * 0-6'
  push:
    branches: ['main']

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  getfile:
    # name: "node fetch lasted file"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0
      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      # - name: "get remote file (clone)"
      #   run: git clone git@github.com:ZYFXS/ZYFXS001.git
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # can not use in github actions
      # - name: fetch file from  https://github.com/ZYFXS/ZYFXS001
      #   run: git subtree pull git@github.com:ZYFXS/ZYFXS001.git main --prefix=src/sub

      - name: install chrome
        run: bunx puppeteer browsers install

      - name: Install dependencies
        run: bun install

      - name: 'get lasted file and move to dist'
        run: bun ./src/index.ts

      - name: 'upload ...'
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: getfile
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy file
        id: deployment
        uses: actions/deploy-pages@v2
